[tox]
isolated_build = true
envlist = py39,py311,py313
# 禁用 “静默跳过”。当缺少指定版本的Python时，立即报错并退出。
skip_missing_interpreters = false

[testenv]
# 基于外部的命令（基于全局依赖）
whitelist_externals = pytest
commands =
    pytest -s {posargs}
