[tox]
# 启用隔离环境
isolated_build = true
# 定义测试矩阵（需要你的系统里已经全局安装了对应版本的Python）
envlist = python3.9,python3.11,python3.14

[testenv]
# 让 tox 知道有哪些可用的外部命令（必须显示声明）
whitelist_externals = pytest
commands =
    pytest -s {posargs}
