[tox]
isolated_build = true
# 需要先手动安装Python，请使用 uv python install <版本号>
envlist = py39,py311,py313
# 禁用 “静默跳过”。当缺少指定版本的Python时，立即报错并退出。
skip_missing_interpreters = false

[testenv]
# 基于外部的命令（基于全局依赖）
whitelist_externals = pytest
# 使用 uv 安装，并指向公司私库
install_command = pip install --index-url https://nexus.asiic.cn/repository/pypi-proxy/simple --timeout 60 --retries 3 {opts} {packages}
commands =
    pytest -s {posargs}
